---
name: "IPMItool server (TEST)"
version: "1.4.0"
slug: "ipmi-server-test"
description: "IPMItool server test"
url: "https://github.com/uberiain/ipmi-addon"
arch:
  - aarch64
  - amd64

panel_icon: "mdi:server"
init: false
hassio_api: true
ingress: true
ingress_stream: true

options:
  log_level: "info"

schema:
  log_level: "list(trace|debug|info|notice|warning|error|fatal)"

ports:
  80/tcp: 9595

ports_description:
  80/tcp: "Not required for Ingress"

image: "ghcr.io/uberiain/ipmi-server-test/{arch}"
